20200120-drivetrain merge with 20200130-drivetrain
NASAKnights/InfiniteRecharge pull request #14
Opened 2020-01-30 23:01 UTC by LeviWalker

Merge 20200120-drivetrain into 20200130-drivetrain

2020-01-30 23:43 UTC, bhooten commented on src/main/java/xyz/nasaknights/infiniterecharge/commands/drivetrain/VisionDriveAssistCommand.java
> +    {
```suggestion
    {
        addRequirements(RobotContainer.getDrivetrain());
```

2020-01-30 23:43 UTC, bhooten commented on src/main/java/xyz/nasaknights/infiniterecharge/commands/drivetrain/VisionDriveAssistCommand.java
> +
```suggestion
import xyz.nasaknights.infiniterecharge.RobotContainer;
```

2020-01-30 23:43 UTC, bhooten approved these changes

2020-01-30 23:45 UTC, bhooten requested changes
Changes need to be tested before committing

2020-02-07 17:28 UTC, LeviWalker commented
This code has been tested on the robot and is ready to merge.

2020-02-22 20:42 UTC, merged

2020-02-22 20:43 UTC, bhooten commented
This branch is stale and was superseded in PR #18. Closed.